version: '3.9'

volumes:
  next-js-data:

services:
  next-js:
    image: node:14.17.0-alpine3.13
    container_name: next-js
    build: .
    ports:
      - 3000:3000
    volumes:
      - next-js-data:/usr/src/app
    restart: always
