version: '3.9'

volumes:
  next-js-data:

# secrets:
#   isoadCa:
#     name: ${ISOADCA_SSL_CERT_SECRET_NAME}
#     file: ${ISOADCA_SSL_CERT_SECRET_FILE}

services:
  app:
    image: ${DOCKER_REGISTRY}/${IMAGE_NAME}:${GIT_COMMIT}
    ports:
      - target: 3000
        published: 3002
        protocol: tcp
        mode: host
    volumes:
      - next-js-data:/usr/src/app






