version: '3.9'

volumes:
  next-js-data:

services:
  app:
    image: ${DOCKER_REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
    volumes:
      - next-js-data:/usr/src/app




