import { useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import { Source_Sans_Pro } from "@next/font/google";

const sourceSansPro = Source_Sans_Pro({
  subsets: ["latin"],
  weight: "700",
  style: "normal",
});

export default function Home() {
  const [isDark, setIsDark] = useState(false);
  const [countries, setCountries] = useState<Array<any>>([]);

  const toggleDarkMode = () => {
    setIsDark(!isDark);
  };

  useEffect(() => {
    if (localStorage.getItem("countries")) {
      return;
    }

    const getData = async () => {
      let allCountry = await fetch("https://restcountries.com/v3.1/all");
      let response: Array<any> = await allCountry.json();
      if (response) {
        localStorage.setItem("countries", JSON.stringify(response));
      }
    };
    getData();
  }, []);

  useEffect(() => {
    const getData = async () => {
      let allCountry = await JSON.parse(localStorage.getItem("countries") || "[]");
      if (allCountry) {
        setCountries(allCountry);
      }
    };
    getData();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={`${sourceSansPro.className}`}>
        <div className={`container mx-auto mx-7xl p-4`}>
          <div className='grid grid-cols-1 sm:grid-cols-2 my-8'>
            <div className='grid-span-1'>
              <button
                onClick={toggleDarkMode}
                className={`${
                  isDark
                    ? "bg-white text-gray-900 w-48 px-4 py-2 rounded-lg"
                    : "bg-gray-900 text-white w-48 px-4 py-2 rounded-lg"
                } w-48 px-4 py-2 rounded-lg`}>
                {isDark ? "Light Mode" : "Dark Mode"}
              </button>
            </div>
          </div>
          <div className='grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4'>
            {countries.map((country: any, index: number) => (
              <div
                key={index}
                className={`rounded-lg p-4 ${isDark ? "bg-white text-gray-900" : "bg-gray-900 text-white"}`}>
                <Image
                  src={country.flags.svg}
                  width={150}
                  height={100}
                  alt={country.name.common}
                  style={{ width: 150, height: 100 }}
                  priority={true}
                />
                <p className='text-xl font-bold'>{country.name.common}</p>
              </div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
